### PR TITLE
Add support for ~/.config/hey/conf.toml configuration file

### PR DESCRIPTION
**Pull request by k-aito**
Hello

I added the support of the configuration file that can be used by `hey`. I think it's ok to use the same one because the inspiration is the same.

Don't hesitate to modify anything if needed, and thank you for the interactive part ^^

Cheers

### CODE REVIEW

**Comment by mrgick** [comment]
Hello, sorry for the long reply, I think this is a good idea.  
Thanks for the code @k-aito

Did a few refactoring:
- Replaced os with pathlib (more modern way in the python) and theoretically, even a windows user will be able to run it
- I removed unnecessary if - made one return ModelType.Claude

Also, if you would have any new ideas - can make new PRs)

**Comment by k-aito** [comment]
Hello @mrgick 

You are welcome, I don't use much Python so it's more like "working" but surely not properly done ^^

I have a few ideas, I will try to implement them and do a PR like this one, doing 1 PR per feature to avoid too big PR.

**Comment by mrgick** [comment]
It will be good, I will wait))

**Comment by mrgick** [comment]
I also made [first release](https://github.com/mrgick/duckduckgo-chat-ai/releases/tag/1.0.0) 

In the future, if you will make a new PR - you can raise the version in [__init__.py](https://github.com/mrgick/duckduckgo-chat-ai/blob/main/duck_chat/__init__.py)

**Comment by k-aito** [comment]
Ok thanks I will do that, I think I will try to add some multiline support for the next PR. I have some idea, but I need to find something that works well.

**Pull request merged**
